- dev/dev_web/auth_overrides.ex
- dev/dev_web/router.ex
- lib/ash_authentication_phoenix/components/banner.ex
- lib/ash_authentication_phoenix/components/horizontal_rule.ex
- lib/ash_authentication_phoenix/components/oauth2.ex
- lib/ash_authentication_phoenix/components/password.ex
- lib/ash_authentication_phoenix/components/password/input.ex
- lib/ash_authentication_phoenix/components/password/register_form.ex
- lib/ash_authentication_phoenix/components/password/reset_form.ex
- lib/ash_authentication_phoenix/components/password/sign_in_form.ex
- lib/ash_authentication_phoenix/components/sign_in.ex
- lib/ash_authentication_phoenix/overrides.ex
- lib/ash_authentication_phoenix/overrides/default.ex
- lib/ash_authentication_phoenix/overrides/overridable.ex
- lib/ash_authentication_phoenix/router.ex
- lib/ash_authentication_phoenix/sign_in_live.ex
This means that if you are customising the default components you can remove the configuration from your `config.exs` and instead move it to your router.  This allows you to have multiple sign-in routes with different "themes" should that be necessary.
> feat(Overrides): Move overrides from application environment to the `sign_in_route` macro.

- README.md
- config/dev.exs
- documentation/tutorials/getting-started-with-ash-authentication-phoenix.md
Will update the readme to point to the the new tutorial once it is published.
Unfortunately, unlike hexdocs, we don't have a great system for publishing updates to documentation without creating a new version, so I've tagged this as an `improvement` to trigger a new version release. Wouldn't normally do this but it looks like lots of people are reading the README.md and not the tutorial
> improvement: remove readme contents, add tutorial

- lib/ash_authentication_phoenix/router.ex
Allows users to add their own `on_mount` hooks for the `reset_routes` macro.
Using this in order to allow browser based testing with [Wallaby](https://github.com/elixir-wallaby/wallaby) on the forgot your password flow.
> feat: Allow on_mount for reset_routes for browser testing

- documentation/tutorials/getting-started-with-ash-authentication-phoenix.md
I tried following this guide and kept running into this error
> The resource `Example.Accounts.User` does not define an attribute named `:unique_email`
After some fumbling around I discovered that the "Getting started with Ash Authentication" guide from Ash Authentication shows `identity_field :email` instead of `identity_field(:unique_email)` [here](https://github.com/team-alembic/ash_authentication/blob/eacda39a00d92c14032b64b40176855eeb82e0bc/documentation/tutorials/getting-started-with-authentication.md?plain=1#L180). With this small change the error stopped showing up and my code started to work.
Still very new to Ash so please let me know if I'm missing something.
> docs: fix `identity_field` in User example

- dev/dev_web/live/custom_sign_in_live.ex
- dev/dev_web/live/home_page_live.ex
- dev/dev_web/router.ex
- lib/ash_authentication_phoenix/components/password.ex
- lib/ash_authentication_phoenix/components/password/register_form.ex
- lib/ash_authentication_phoenix/components/password/reset_form.ex
- lib/ash_authentication_phoenix/components/password/sign_in_form.ex
Allows the sign in, register and reset forms to be customised by way of a named slot.
> improvement: Add slots to password-related forms.

- lib/ash_authentication_phoenix/components/reset.ex
- lib/ash_authentication_phoenix/router.ex
Overrides weren't getting added to the live session in the same way as `sign_in`, so this harmonizes implementations for the `sign_in` route macro with `reset_route` macro. It also passes a missing `@overrides` assigns to the Banner in the Reset component.
> fix: Overrides in reset route

- lib/ash_authentication_phoenix/components/password/register_form.ex
- mix.exs
So, we might need to make this configurable, but based on my last comment here https://github.com/team-alembic/ash_authentication_phoenix/issues/269 I'm not sure it really matters. The responsibility for keeping bad actors out in this scenario would likely have to be in a plug or some kind of rate limiting logic. The "attacker" could use the fact that they got an error to suss out that they've hit on a username that exists anyway.
> improvement: submit form in-line when sign_in_tokens_enabled

- documentation/tutorials/getting-started-with-ash-authentication-phoenix.md
- lib/ash_authentication_phoenix/components/password.ex
- lib/ash_authentication_phoenix/components/password/register_form.ex
- lib/ash_authentication_phoenix/components/sign_in.ex
- lib/ash_authentication_phoenix/router.ex
- lib/ash_authentication_phoenix/sign_in_live.ex
Fixes: #98 
This slightly special cases registration and reset. In the future we may want something more generic, but this is the only current case we have for strategy customizable links. Seemed simplest to do it this way for now.
> improvement: optional support for routing to register & reset links

- lib/ash_authentication_phoenix/router.ex
The docstring contained the `register_path` parameter twice and forgot to include the `reset_path` parameter.
> Fix some copypasta in the sign_in_route/1 docstring

- lib/ash_authentication_phoenix/components/password.ex
We were using the `get_by_subject_action_name` instead of the `subject_name`.  Oops.
Fixes #108.
> fix: incorrect introspection target in password strategy.

- lib/ash_authentication_phoenix/components/banner.ex
- lib/ash_authentication_phoenix/components/horizontal_rule.ex
- lib/ash_authentication_phoenix/components/magic_link.ex
- lib/ash_authentication_phoenix/components/oauth2.ex
- lib/ash_authentication_phoenix/components/password.ex
- lib/ash_authentication_phoenix/components/password/input.ex
- lib/ash_authentication_phoenix/components/password/register_form.ex
- lib/ash_authentication_phoenix/components/password/reset_form.ex
- lib/ash_authentication_phoenix/components/password/sign_in_form.ex
- lib/ash_authentication_phoenix/components/reset.ex
- lib/ash_authentication_phoenix/components/reset/form.ex
- lib/ash_authentication_phoenix/components/sign_in.ex
- lib/ash_authentication_phoenix/reset_live.ex
- lib/ash_authentication_phoenix/sign_in_live.ex
- lib/ash_authentication_phoenix/templates/live.html.heex
- lib/ash_authentication_phoenix/utils/flash.ex
- lib/ash_authentication_phoenix/views/layout_view.ex
- lib/ash_authentication_phoenix_web.ex
**The Issue**
Flash messages not being rendered in scenarios like submitting the reset password form, telling the user that the request has been received.
**The Reason**
There are actually two reasons:
1) Our liveviews are rendering inside the root layout of the parent app, but the main layout (eg. `live` or `app`) was not being set.
A fresh generated Phoenix app [has the flash messags within those layouts](https://github.com/team-alembic/ash_authentication_phoenix/blob/main/dev/dev_web/templates/layout/live.html.heex), and defines the layout to use [when using the Phoenix.LiveView macro](https://github.com/team-alembic/ash_authentication_phoenix/blob/main/dev/dev_web.ex#L49-L50).
So now our liveviews do the same. Instead of using Phoenix.LiveView, with no layout configured, they use …
> fix: Render flash messages and provide a default implementation

- lib/ash_authentication_phoenix/router.ex
Ensure that `AshAuthentication.Phoenix.LiveSession` is included in the `on_mount` of the generated live sessions.
> fix: Ensure that `sign_in_route` and `reset_route` correctly initialise session.

- lib/ash_authentication_phoenix/ash_phoenix_errors.ex
When the field being validated is not the strategy's password field then don't show the normal validation message.
Closes #334
> fix: honour the error field in AuthenticationFailed errors in forms.

- documentation/tutorials/get-started.md
This pull request fixes issues with the policy authorizer setup instructions in the tutorial.
The first commit adds a missing import to a couple sections. The second commit adds instructions for adding the `picosat_elixir` solver. The content for the second pull request was taken from the main Ash tutorial.
> docs: change tutorial to help enable policy authorizers

- lib/ash_authentication_phoenix/overrides/overridable.ex
> fix: use any overridden value, including `nil` or `false`

- lib/ash_authentication_phoenix/components/password/input.ex
- lib/ash_authentication_phoenix/overrides/default.ex
Added overrides for identity (email) and password fields.  Labels can be set using a string or an atom.
> Added overrides for identity (email) and password fields. 

- documentation/tutorials/liveview.md
Change the title to "Setting up your routes for LiveView" instead of just "Setting up your routes", since the guide is specifically about LiveView.
> Clarify tutorial name

- lib/ash_authentication_phoenix/router.ex
This fixes #489 by ensuring that the session options reflect the scoped path by using ```Phoenix.Router.scoped``` rather than just the literal string path passed into the helper.
> fix: Ensure session respects router scope when using sign_in_route helper

- lib/ash_authentication_phoenix/components/password/input.ex
- lib/ash_authentication_phoenix/overrides/default.ex
Using the same name for the labels and fields allows the fields to be focussed by clicking on the label.
Also fixed a quirk where the same label key was used for both Password and Password confirmation fields.
> fix: Re-link form labels and form inputs on Password strategy forms

- lib/ash_authentication_phoenix/components/apple.ex
- lib/ash_authentication_phoenix/components/sign_in.ex
- lib/ash_authentication_phoenix/overrides/default.ex
Adds a new button component for the Apple strategy.
Apple's guidelines for the design of the button are fairly strict, so I went with creating a new component instead of extending the existing OAuth component.
> improvement: add button for the Apple strategy

- lib/mix/tasks/ash_authentication_phoenix.install.ex
- test/mix/tasks/ash_authentication_phoenix.install_test.exs
It's kind of a lame user experience that there are no flash messages by default for things like login, confirm password, etc. This adds some reasonable enough defaults, so that new users running `ash_authentication_phoenix.install` get some in their AuthController.
Note that there isn't currently a way to distinguish between sign in/register using the activity, as it's `{:password, :sign_in_with_token}` for both due to LiveView shenanigans.
> feat: Add action-specific flash messages to the generated AuthController

- lib/ash_authentication_phoenix/components/password/input.ex
- lib/ash_authentication_phoenix/components/reset/form.ex
- lib/ash_authentication_phoenix/components/sign_in.ex
Some small tweaks, for:
Positioning of the Magic Link form
| Before | After |
| ------- | ------ |
| <img width="446" alt="Screenshot 2024-11-12 at 12 14 02 PM" src="https://github.com/user-attachments/assets/7dbfa2a8-d90e-429d-899e-677e70d0c91d"> | <img width="471" alt="Screenshot 2024-11-12 at 12 17 45 PM" src="https://github.com/user-attachments/assets/9300a214-ca96-42f1-a13b-161b5de58f07"> |
Text for Password Reset button
| Before | After | 
| ------- | ------ |
| <img width="446" alt="Screenshot 2024-11-12 at 12 18 15 PM" src="https://github.com/user-attachments/assets/8f342eef-e793-44c9-8870-7ab2ad1f35ec"> | <img width="436" alt="Screenshot 2024-11-12 at 12 18 00 PM" src="https://github.com/user-attachments/assets/b39379c5-a967-4bca-a005-57241764e9b1"> |
> chore: Tweak UI styling

- lib/mix/tasks/ash_authentication_phoenix.install.ex
- test/mix/tasks/ash_authentication_phoenix.install_test.exs
Without this, only the default override values are used!
> fix: Apply overrides to password reset update form in Igniter-generated routes

- lib/ash_authentication_phoenix/components/password/reset_form.ex
- Added logic to set the current tenant on the `Ash.Query` in `handle_event/3` for the `Password.ResetForm` component.
- Fixes `FunctionClauseError` caused by unmatched query structures during password reset events.
Fixed Error screenshot
> fix: handle tenant-specific query in Password Reset Form handle_event/3

- lib/mix/tasks/ash_authentication_phoenix.install.ex
The generated `auth_controller.ex` file contains a small error. The message in the `failure` function is not used.
This PR uses the proper message.
> Set the expected message in failure function.

- documentation/tutorials/ui-overrides.md
- i18n/gettext/auth.pot
- i18n/gettext/de/LC_MESSAGES/auth.po
- lib/ash_authentication_phoenix/components/apple.ex
- lib/ash_authentication_phoenix/components/banner.ex
- lib/ash_authentication_phoenix/components/magic_link.ex
- lib/ash_authentication_phoenix/components/oauth2.ex
- lib/ash_authentication_phoenix/components/password.ex
- lib/ash_authentication_phoenix/components/password/input.ex
- lib/ash_authentication_phoenix/components/password/register_form.ex
- lib/ash_authentication_phoenix/components/password/reset_form.ex
- lib/ash_authentication_phoenix/components/password/sign_in_form.ex
- lib/ash_authentication_phoenix/components/reset.ex
- lib/ash_authentication_phoenix/components/reset/form.ex
- lib/ash_authentication_phoenix/components/sign_in.ex
- lib/ash_authentication_phoenix/overrides/default.ex
- lib/ash_authentication_phoenix/reset_live.ex
- lib/ash_authentication_phoenix/router.ex
- lib/ash_authentication_phoenix/sign_in_live.ex
- lib/ash_authentication_phoenix_web.ex
- lib/mix/tasks/ash_authentication_phoenix.install.ex
- mix.exs
- test/password_reset_test.exs
- test/router_test.exs
- test/sign_in_test.exs
- test/support/phoenix.ex
- test/test_helper.exs
A simple wrapper to invoke gettext if available.
Would solve #110, #559.
What you think of this implementation?
Missing: Tests, default .pot, maybe .po files, docs
> Gettext i18n

- lib/ash_authentication_phoenix/components/apple.ex
- lib/ash_authentication_phoenix/components/banner.ex
- lib/ash_authentication_phoenix/components/magic_link.ex
- lib/ash_authentication_phoenix/components/oauth2.ex
- lib/ash_authentication_phoenix/components/password.ex
- lib/ash_authentication_phoenix/components/password/input.ex
- lib/ash_authentication_phoenix/components/password/register_form.ex
- lib/ash_authentication_phoenix/components/password/reset_form.ex
- lib/ash_authentication_phoenix/components/password/sign_in_form.ex
- lib/ash_authentication_phoenix/components/reset.ex
- lib/ash_authentication_phoenix/components/reset/form.ex
- lib/ash_authentication_phoenix/components/sign_in.ex
- lib/ash_authentication_phoenix/router.ex
- test/components_test.exs
- test/password_reset_test.exs
- test/sign_in_test.exs
- test/support/accounts/user.ex
- test/support/components_live.ex
- test/support/helper.ex
- test/support/phoenix.ex
(based on #564)
Components were missing a default `gettext_fn`, complaining without.
Test included.
> Gettext components fix

- documentation/tutorials/ui-overrides.md
- Include `dark_image_url` in example
- Explain corresponding dark mode properties and that you should set them
- Updated reference list to point to dark_mode counterpart.
Related to #568
> docs: improve dark mode override documentation

- documentation/tutorials/ui-overrides.md
- lib/ash_authentication_phoenix/components/sign_in.ex
- lib/ash_authentication_phoenix/overrides/default.ex
Addresses #590 by adding override options for the order that the strategies can be displayed
> feat: Display order for strategies in sign in page

- documentation/tutorials/get-started.md
This PR updates the documentation for manually installing ash_authentication_phoenix. It includes Plug helpers and macros that would have been added via the igniter installation.
> docs: Update documentation for manual installation

- lib/ash_authentication_phoenix/components/password/sign_in_form.ex
There's not really a good reason that AA slugifies the subject name when looking for params, but it does, so in order to not break backwards compatibility we modify the form to match.
Thanks to @adamtharani for being the first person to notice this!
> fix(Password.SignInForm): Slugify the form param to match what AA expects

- documentation/tutorials/ui-overrides.md
- lib/ash_authentication_phoenix/components/password.ex
- lib/ash_authentication_phoenix/overrides/default.ex
A way to override the whole registration for as to allow any customization of it.
In the screenshot below we are adding a "name" field on the top
> feat: Add override option for register form

- lib/ash_authentication_phoenix/live_session.ex
- lib/ash_authentication_phoenix/router.ex
For hooks that need to be run before `AshAuthentication.Phoenix.Router.OnLiveViewMount`, for example to set up SQL sandboxing for LiveView.
Further background: https://elixirforum.com/t/sql-sandboxing-issue-with-phoenix-playwright/71093/27
> feat: add on_mount_prepend option

- documentation/tutorials/ui-overrides.md
- lib/ash_authentication_phoenix/components/password.ex
- lib/ash_authentication_phoenix/overrides/default.ex
[Discord #ash_authentication channel](https://discord.com/channels/711271361523351632/1253437793053577226/1387036675904897074)
This is the same thing with https://github.com/team-alembic/ash_authentication_phoenix/pull/602 ("A way to override the whole registration for as to allow any customization of it."), but adding options to both reset and sign in for full customization.
> Add override options to reset and sign in forms

- lib/ash_authentication_phoenix/components/magic_link/input.ex
- lib/ash_authentication_phoenix/overrides/default.ex
This PR adds `submit_label` override for the magic link input/sign in which wasn't being used
> fix: add missing override for magic link input submit_label

- dev/dev_web/router.ex
- dev/dev_web/templates/layout/root.html.heex
- lib/mix/tasks/ash_authentication_phoenix.install.ex
- test/mix/tasks/ash_authentication_phoenix.install_test.exs
* switches install to use daisyui overrides when using daisyui
* switches included test app to use daisyui overrides
~~Not sure if we wanted to do something like:~~
~~* check phoenix version, use daisyui overrides if 1.8+ otherwise default~~
~~* or just wait until phoenix 1.8 is released proper to merge~~
~~* add separate test app pages for default/daisyui overrides~~
> improvement: install with daisyUI overrides if using daisyUI
