team-alembic/ash_authentication_phoenix

- lib/ash_authentication_phoenix/components/banner.ex
- lib/ash_authentication_phoenix/overrides/default.ex
likely more will be necessary, but these make the login page look better
> improvement: add some dark mode fixes

- mix.exs
Went through all of that rigamarole to release a new version to get the docs released and I didn't update the docs info in `mix.exs` so it didn't change anything. Great 🥳
> chore: add extras in mix.exs

- lib/ash_authentication_phoenix/overrides/default.ex
- lib/ash_authentication_phoenix/overrides/info.ex
> improvement: improve default theme on dark mode.

- documentation/tutorials/getting-started-with-ash-authentication-phoenix.md
Deletes one duplicate entry and fixes a file path.
> docs: Bugfixes in the tutorial

- lib/ash_authentication_phoenix/components/password.ex
- lib/ash_authentication_phoenix/components/password/input.ex
Resolves #97 , if that's of interest.
> improvement: Autofocus identity field in password component

- documentation/tutorials/getting-started-with-ash-authentication-phoenix.md
> docs: Fix typo

- documentation/tutorials/getting-started-with-ash-authentication-phoenix.md
The only piece I'm not clear on with this one is the change on the identity from `unique_email` to `email`, as there seems like there is a bit of inconsistency on that one in the docs.
> Updates documentation to nest in the resources folder

- documentation/tutorials/getting-started-with-ash-authentication-phoenix.md
> docs: fix incorrect example in getting started guide.

- lib/ash_authentication_phoenix/live_session.ex
This is a breaking change.
LiveView module provides [`assign_new`](https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#assign_new/3) method. It allows sharing set assigned values between plugs, dead, live and nested mounts. The method can be used (as it was designed for cases like) in `AshAuthentication.Phoenix.LiveSession.on_mount` to set "current_" assigns.
But `assign_new` cannot skip setting value. So current behavior for when `subject_to_user` does not success and nothing is set cannot be replicated. If there were no user found "current_thing" will be set to `nil`.
Another change is that iteration happens not on session entries but on authorization resources. It means that "current_user" assign is always set to nil or to a found record. So the problem listed in documentation …
> feat: change `ash_authentication_live_session` to use `assign_new`

- documentation/tutorials/getting-started-with-ash-authentication-phoenix.md
> Documentation polish 🧽

- documentation/tutorials/getting-started-with-ash-authentication-phoenix.md
Moved up the LiveView tutorial link because if you proceed with LiveView in your project but not setting it up, Phoenix will crash during the Start Phoenix step.
This caused me to get stuck thinking that I had done something wrong, when I hadn't. The only problem was that I had not yet setup LiveView, which the tutorial does not get to until the very end.
> docs(Improvements): Move the LiveView section up because if you do not set it up, Phoenix will crash in the next step.

- lib/ash_authentication_phoenix/components/password.ex
> fix: properly navigate back to root component when routes are not set

- documentation/tutorials/getting-started-with-ash-authentication-phoenix.md
Remove `api` function
Tidy up some other outdated text.
> Update guide for domains rather than apis

- documentation/tutorials/get-started.md
This pull request just changes the directory structure to match the other newer examples I have seen.
Please double check this for me to ensure it is accurate.
Thanks
> docs: use new directory structure for resources

- documentation/tutorials/get-started.md
Just piggybacking off the same change made in the `ash_authentication` repo:
https://github.com/team-alembic/ash_authentication/commit/b9a81770f3f25822faf6485deac6a80dd84d7d73
> docs: you have to explicitly turn on token generation

- documentation/tutorials/get-started.md
And add a small note about being able to rename the User resource.
I went through this guide today and am trying to add a note about custom Use resource names. Please feel free to hint at better wording wherever needed.
> Update tutorial to move from api -> domains

- lib/ash_authentication_phoenix/overrides/list.ex
Change passoword to password, since it shows up in hex docs
> Update spelling in list.ex

- lib/ash_authentication_phoenix/plug.ex
This PR continues the work initiated in https://github.com/team-alembic/ash_authentication/issues/846.
> Pass opts of plugs to retrieve helpers

- lib/ash_authentication_phoenix/components/reset/form.ex
This PR is a follow-up to the work missed in #562.
> Allow changing button text of Reset.Form

- i18n/gettext/sv/LC_MESSAGES/auth.po
Love the added internationalization 🎈 
I went ahead and created this PR for my own native language, Swedish. I hope an unannounced PR of this nature is not unwelcomed.
I don't know any other native Swedes using Ash who could review, but if you have anyone on file that would be great 🙂
Pretty sure it's solid though.
> Add Swedish translation

- lib/ash_authentication_phoenix/components/reset.ex
> fix: Add strategy name to reset form IDs.

- documentation/tutorials/get-started.md
see also https://github.com/team-alembic/ash_authentication/issues/708
> docs: get-started: add note regarding AuthController.failure
